namespace ProjectEvolution.Game;

/// <summary>
/// Maps game objects to procedurally generated tile IDs (Ultima IV style)
/// NO EXTERNAL DEPENDENCIES - All tiles generated by ProceduralTileGenerator
/// </summary>
public static class TileMapper
{
    // ═══════════════════════════════════════════════════════════════
    // TERRAIN TILES (Procedurally Generated - Ultima IV Style)
    // ═══════════════════════════════════════════════════════════════

    public static readonly int GRASS_TILE = 0;           // Grassland - vibrant green with texture
    public static readonly int FOREST_TILE = 1;          // Forest - dark green with tree
    public static readonly int MOUNTAIN_TILE = 2;        // Mountain - gray triangle with snow peak
    public static readonly int WATER_TILE = 3;           // Water - blue with wave pattern

    // ═══════════════════════════════════════════════════════════════
    // STRUCTURE TILES
    // ═══════════════════════════════════════════════════════════════

    public static readonly int TOWN_TILE = 10;           // Town - simple building (brown walls, red roof)
    public static readonly int TEMPLE_TILE = 11;         // Temple - golden structure with 3 pillars
    public static readonly int DUNGEON_ENTRANCE = 12;    // Dungeon - dark opening with stone arch

    // ═══════════════════════════════════════════════════════════════
    // CHARACTER TILES
    // ═══════════════════════════════════════════════════════════════

    public static readonly int PLAYER_TILE = 20;         // Player - stick figure (circle head, body, arms, legs)
    public static readonly int NPC_TILE = 21;            // NPC - similar to player but blue clothing

    // ═══════════════════════════════════════════════════════════════
    // ENEMY/MOB TILES
    // ═══════════════════════════════════════════════════════════════

    public static readonly int GOBLIN = 30;              // Goblin - green creature with eyes and ears
    public static readonly int UNDEAD = 31;              // Undead - pale skeleton with skull and ribcage
    public static readonly int DEMON = 32;               // Demon - red figure with horns
    public static readonly int BEAST = 33;               // Beast - brown animal (wolf/bear style)

    // ═══════════════════════════════════════════════════════════════
    // ITEM TILES
    // ═══════════════════════════════════════════════════════════════

    public static readonly int POTION = 40;              // Potion - red bottle with cork and highlight
    public static readonly int GOLD = 41;                // Gold - golden coins (3 circles)
    public static readonly int TREASURE_CHEST = 42;      // Chest - brown with curved lid and gold lock

    // ═══════════════════════════════════════════════════════════════
    // DUNGEON TILES
    // ═══════════════════════════════════════════════════════════════

    public static readonly int DUNGEON_WALL = 50;        // Wall - gray stone with brick pattern
    public static readonly int DUNGEON_FLOOR = 51;       // Floor - dark stone with subtle cracks
    public static readonly int STAIRS_DOWN = 52;         // Stairs - ">" symbol

    // ═══════════════════════════════════════════════════════════════
    // MAPPING FUNCTIONS
    // ═══════════════════════════════════════════════════════════════

    /// <summary>
    /// Get the tile ID for a terrain type
    /// </summary>
    public static int GetTerrainTileId(string terrain)
    {
        return terrain switch
        {
            "Grass" or "Grassland" => GRASS_TILE,
            "Forest" => FOREST_TILE,
            "Mountain" => MOUNTAIN_TILE,
            "Water" => WATER_TILE,
            "Town" => TOWN_TILE,
            "Dungeon" => DUNGEON_ENTRANCE,
            "Temple" => TEMPLE_TILE,
            _ => GRASS_TILE  // Default to grass
        };
    }

    /// <summary>
    /// Get the tile ID for a dungeon tile
    /// </summary>
    public static int GetDungeonTileId(string tileType)
    {
        return tileType switch
        {
            "Floor" => DUNGEON_FLOOR,
            "Wall" => DUNGEON_WALL,
            "Stairs" => STAIRS_DOWN,
            "Monster" => GOBLIN,             // Will be replaced by actual monster
            "Treasure" => TREASURE_CHEST,
            "Trap" => DUNGEON_FLOOR,         // Trap looks like floor until triggered
            "Boss" => DEMON,                 // Boss tile
            "Artifact" => GOLD,              // Artifact (shiny)
            "Portal" => STAIRS_DOWN,         // Portal (use stairs for now)
            _ => DUNGEON_FLOOR
        };
    }

    /// <summary>
    /// Get the tile ID for a mob based on enemy type
    /// </summary>
    public static int GetMobTileId(EnemyType enemyType)
    {
        return enemyType switch
        {
            // Goblins (all use goblin tile)
            EnemyType.GoblinScout => GOBLIN,
            EnemyType.GoblinWarrior => GOBLIN,
            EnemyType.GoblinArcher => GOBLIN,

            // Undead
            EnemyType.Skeleton => UNDEAD,
            EnemyType.Zombie => UNDEAD,
            EnemyType.Wraith => UNDEAD,

            // Beasts
            EnemyType.Wolf => BEAST,
            EnemyType.Bear => BEAST,
            EnemyType.Serpent => BEAST,

            // Demons
            EnemyType.Imp => DEMON,
            EnemyType.Hellhound => DEMON,
            EnemyType.Demon => DEMON,

            _ => GOBLIN  // Default to goblin
        };
    }

    /// <summary>
    /// Get the tile ID for a mob based on level (for variety)
    /// </summary>
    public static int GetMobTileByLevel(int level)
    {
        return level switch
        {
            <= 5 => GOBLIN,
            <= 10 => UNDEAD,
            <= 15 => BEAST,
            _ => DEMON
        };
    }

    /// <summary>
    /// Get random mob tile for variety
    /// </summary>
    public static int GetRandomMobTile(Random random, int level)
    {
        if (level <= 5)
            return GOBLIN;
        else if (level <= 12)
            return random.Next(2) == 0 ? UNDEAD : BEAST;
        else
            return DEMON;
    }
}
